config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'user/profile/edit' => 'registrations#profile', as: "registrations_profile_edit"
  end

  resources :users, only: [:show]
  resources :movies, only: [:new]
  resources :reviews do 
    collection do 
      get 'search'
      get 'filter'
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :check_admin, only: [:new]

  require 'http'
  require 'json'  

  def new
    @reviews = Review.all 
    @results = params[:movie_query].present? ? JSON.parse(HTTP.get("https://www.omdbapi.com/?apikey=#{ENV['MOVIE_API_KEY']}&s=#{params[:movie_query]}"))['Search'] : []
  end

  private 
  
  def check_admin
    unless current_user.admin?
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to user_path(current_user)
    end
  end
end

app/views/movies/new.html.erb
<div class="min-h-screen flex flex-col items-center bg-slate-200">
  <%= render partial: 'devise/shared/navbar'%>
  <div class="mt-10 flex flex-col w-4/5 justify-center items-center top-14 md:top-20 relative">
    <h3 class="font-bold text-lg w-4/5 text-center">What movie would you like to review?</h3>
    <%= form_with url: new_movie_path, class:"w-3/4 mt-3 flex justify-center max-w-3xl", method: :get do |form| %>
      <%= form.text_field :movie_query, class: "rounded w-full max-w-lg", placeholder: "Search for movie" %>
      <button class="hidden md:inline ml-3 bg-blue-600 hover:bg-blue-700 text-white font-normal py-2 px-4 rounded focus:outline-none focus:shadow-outline">
       <%= form.submit 'Search', class:"hover:cursor-pointer" %>
      </button>
    <% end %>
  </div>
  <% if !params[:movie_query].blank? && (@results.nil? || !@results.any?) %>
    <h2 class="font-bold text-lg mt-28 text-center max-w-md">No results for "<%= params[:movie_query] %>"</h2>
  <% elsif @results.any? %>
    <h2 class="font-bold text-lg mt-28 text-center max-w-md">Showing results for "<%= params[:movie_query] %>"</h2>
    <div class="mt-12 w-11/12 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-4">
      <% @results.each do |result| %>
        <div class="flex flex-col items-center">
          <div class="h-full p-3 w-60 flex flex-col justify-between items-center rounded-lg shadow-md">
            <% if result['Poster'] == 'N/A'%>
              <img src="https://i.ibb.co/xjPnHKf/360-F-400243185-BOx-ON3h9av-MUX10-Rs-Dkt3p-J8i-Qx72k-S3.jpg" alt="No image" class="w-full h-48 object-contain rounded-t-lg">
            <% else %>
              <img src="<%= result['Poster'] %>" alt="No poster available" class="w-full h-48 object-contain rounded-t-lg">
            <% end %>     
            <div class="font-semibold text-center mb-2">
              <%= result['Title'] %>
            </div>         
            <% if Review.exists?(imdb_id: result['imdbID']) %>
              <%= render partial: '/reviews/edit_delete_btns', locals: { id: Review.find_by(imdb_id: result['imdbID']).id } %>
              <%= render partial: '/reviews/delete_modal', locals: { id: Review.find_by(imdb_id: result['imdbID']).id, movie_title: result['Title'] }%>
            <% else %>
              <button class="text-sm hover:bg-blue-700 text-blue-700 border-2 border-blue-400 hover:text-white font-normal py-1 px-3 rounded focus:outline-none focus:shadow-outline">
                <%= link_to "Review", new_review_path(imdb_id: result['imdbID']) %>
              </button>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>