config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'user/profile/edit' => 'registrations#profile', as: "registrations_profile_edit"
  end

  resources :users, only: [:show]
  resources :movies, only: [:new]
  resources :reviews do 
    collection do 
      get 'search'
      get 'filter'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  has_many :reviews 
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, only: [:show]

  def show
    if flash.now[:access_denied].present?
      flash.now[:access_denied] = flash.now[:access_denied]
      redirect_to user_path(current_user)
    end
  end

  private

  def authorize_user
    if current_user.id != params[:id].to_i
      flash[:access_denied] = "You are not authorized to view that page."
      redirect_to user_path(current_user), flash: { access_denied: flash[:access_denied] }
    end
  end
end

app/views/users/edit.html.erb
<div id="pageContainer" class="min-h-screen flex flex-col flex-start bg-slate-200">

  <%= render partial: 'devise/shared/navbar'%>

  <% if session[:access_denied_message] %>
    <div class="alert alert-danger">
      <%= session[:access_denied_message] %>
    </div>
  <% session.delete(:access_denied_message) %>
  <% end %>

  <div class="flex flex-col justify-center items-center">
  
  <h3 class="text-md font-bold m-7">Edit Account</h3>

  </div>

</div>

app/views/users/show.html.erb
<div class="min-h-screen flex flex-col flex-start bg-slate-200">
  <%= render partial: 'devise/shared/navbar'%>
  <% if session[:access_denied_message] %>
    <div class="alert alert-danger">
      <%= session[:access_denied_message] %>
    </div>
  <% session.delete(:access_denied_message) %>
  <% end %>
  <div class="flex flex-col justify-center items-center top-14 md:top-40 relative">
    <h3 class="text-md font-bold m-7">Account Information</h3>
    <% flash.each do |key, value| %>
      <div class="underline my-5 border-black font-bold p-3 flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
    <div class="text-sm md:text-base w-5/6 max-w-xl"> 
      <div class="w-full flex justify-between my-7">
        <span class="font-semibold">Name</span>
        <span><%= current_user.first_name + " " + current_user.last_name %></span>
      </div>
      <div class="w-full flex justify-between my-7">
        <span class="font-semibold">Username</span>
        <span><%= current_user.username %></span>
      </div>
      <div class="w-full flex justify-between my-7">
        <span class="font-semibold">Email</span>
        <span><%= current_user.email %></span>
      </div>
    </div>
    <div class="flex flex-col md:flex-row mt-10 max-w-xl">
      <%= link_to 'Edit Profile', registrations_profile_edit_path, class: "mt-5 text-center bg:white border-2 border-blue-500 hover:bg-blue-500 hover:text-white text-blue-500 font-normal m-1 py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%= link_to 'Password Reset', edit_user_registration_path, class: "mt-5 text-center bg:white border-2 border-blue-500 hover:bg-blue-500 hover:text-white text-blue-500 font-normal m-1 py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>  
</div> 