config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'user/profile/edit' => 'registrations#profile', as: "registrations_profile_edit"
  end

  resources :users, only: [:show]
  resources :movies, only: [:new]
  resources :reviews do 
    collection do 
      get 'search'
      get 'filter'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  require 'http'
  require 'json' 
  
  def index
    @reviews = Review.select(:id, :movie_poster, :movie_title, :review_score).as_json
  end

  def show
    @review = Review.find(params[:id])
  end

  def new   
    @result = params[:imdb_id].present? ? JSON.parse(HTTP.get("https://www.omdbapi.com/?apikey=#{ENV['MOVIE_API_KEY']}&i=#{params[:imdb_id]}")) : []
  end

  def create 
    @review = Review.create(movie_poster: params[:poster], movie_title: params[:title], director: params[:director], writer: params[:writer], genre: params[:genre], runtime: params[:runtime], awards: params[:awards], rated: params[:rated], plot_summary: params[:summary], review_score: params[:score], review_summary: params[:review], release_year: params[:year], actors: params[:actors], imdb_id: params[:imdbID])
    if @review.save 
      redirect_to reviews_path 
    end
  end
  
  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_score: params[:review][:score], review_summary: params[:review][:review])
    redirect_to review_path(@review) if @review.save
  end

  def destroy
    @review = Review.find(params[:id])
    redirect_to reviews_path if @review.destroy
  end

  def search
    @reviews = Review.select(:id, :movie_poster, :movie_title, :review_score).as_json
    @search_results = Review.select(:id, :movie_poster, :movie_title, :review_score).where("LOWER(movie_title) LIKE :query OR LOWER(release_year) LIKE :query OR LOWER(genre) LIKE :query OR LOWER(director) LIKE :query OR LOWER(writer) LIKE :query OR LOWER(actors) LIKE :query", query: "%#{params[:query].downcase.strip.squeeze(" ")}%").as_json
    respond_to do |format|
      format.turbo_stream { render :index }
      format.html { render :index }
    end
  end

  def filter 
    @reviews = Review.select(:id, :movie_poster, :movie_title, :review_score).as_json
    @filter_params = []  
    @filter_params << Review.select(:id, :movie_poster, :movie_title, :review_score).where(release_year: params[:release_year]).as_json if params[:release_year].present?
    @filter_params << Review.select(:id, :movie_poster, :movie_title, :review_score).where(rated: params[:rated]).as_json if params[:rated].present?
    @filter_params << Review.select(:id, :movie_poster, :movie_title, :review_score).where(review_score: params[:review_score]).as_json if params[:review_score].present?
    @filter_params << Review.select(:id, :movie_poster, :movie_title, :review_score).where(Array.new(params[:genre].size, "genre LIKE ?").join(" OR "), *params[:genre].map { |genre| "%#{genre}%" }).as_json if params[:genre].present?
    @filter_params = @filter_params.flatten.uniq
    @params_exist = params[:release_year].present? || params[:genre].present? || params[:rated].present? || params[:review_score].present? 
    
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          'reviews_frame',
          partial: 'movie_layout',
          locals: { reviews: @filter_params }
      )
    end
      format.html { render :index }
    end
  end

  private

  def check_admin
    unless current_user.admin?
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to user_path(current_user)
    end
  end
end

app/views/reviews/_delete.html.erb
<%= tag.div id: "modal-#{review.id}", class: 'delete-modal hidden mt-14 top-0 left-0 fixed bg-opacity-75 bg-zinc-200 h-screen w-screen flex justify-center items-center', data: { review_id: review.id } do %>
  <div class="border-2 border-black bg-white w-3/4 max-w-xl h-auto flex flex-col justify-center items-center p-5">
    <h4 class="font-bold text-center">Delete Review for <%= review.movie_title %>?</h4>
    <div class="mt-3">
      <%= link_to 'Delete', review_path(review.id), data: {turbo_method: :delete}, class:"w-20 mx-3 text-center text-xs text-red-600 border-2 border-red-600 hover:bg-red-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <span onclick="document.getElementById('modal-<%= review.id %>').classList.toggle('hidden');" class="cancel-modal w-20 mx-3 text-center hover:cursor-pointer text-xs text-red-600 border-2 border-red-600 hover:bg-red-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline">Cancel</span>
    </div>
  </div>
<% end %>

app/views/reviews/_delete_modal.html.erb
<%= tag.div id:"modal-#{id}", class: 'delete-modal hidden mt-14 top-0 left-0 fixed bg-opacity-75 bg-zinc-200 h-screen w-screen flex justify-center items-center', data: { review_id: id } do %>
  <div class="border-2 border-black bg-white w-3/4 max-w-xl h-auto flex flex-col justify-center items-center p-5">
    <h4 class="font-bold text-center">Delete Review for <%= movie_title %>?</h4>
    <div class="mt-3">
      <%= link_to 'Delete', review_path(id), data: {turbo_method: :delete}, class:"w-20 mx-3 text-center text-xs text-red-600 border-2 border-red-600 hover:bg-red-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <span onclick="document.getElementById('modal-<%= id %>').classList.toggle('hidden');" class="cancel-modal w-20 mx-3 text-center hover:cursor-pointer text-xs text-red-600 border-2 border-red-600 hover:bg-red-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline">Cancel</span>
    </div>
  </div>
<% end %>

app/views/reviews/_edit_delete_btns.html.erb
<div class="flex justify-center text-xs w-11/12">
  <%= link_to edit_review_path(id), class: "mr-2 border-2 text-green-600 flex-1 rounded-md flex justify-center items-center border-green-600 hover:bg-green-600 hover:cursor-pointer hover:text-white", data: { turbo_frame: "_top" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
      <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
    </svg>
    <span>Edit</span>
  <% end %> 
  <%= content_tag :div, 'Delete', data: { review_id: id }, class: 'ml-2 review-delete border-2 border-black flex-1 flex items-center justify-center bg-red-600 hover:cursor-pointer text-center text-white border-red-600 hover:bg-red-600 hover:text-red-600 hover:bg-white rounded-md focus:outline-none focus:shadow-outline', onclick: "toggleModal(this)" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
      <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
    </svg>
    <span>Delete</span>
  <% end %>
</div> 

app/views/reviews/_filter.html.erb
<%= form_tag filter_reviews_path, id:"filter-form", method: :get, class:"hidden md:w-11/12 max-w-5xl md:flex mt-3 text-base" do %>
  <div class="flex-1">
    <div id="release_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg p-2" onclick="document.getElementById('release_years').classList.toggle('hidden');" >
      <h5 class="text-white">Release Year</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="release_years" class="hidden absolute w-60 z-50 text-gray-200 bg-gray-600 border-2 border-black mt-1 p-1 max-h-52 overflow-scroll rounded-sm">
      <% Review.distinct.order(release_year: :desc).pluck(:release_year).each do |year| %>
        <div class="flex items-center my-1">
          <%= check_box_tag 'release_year[]', year, false, id: "release_year_#{year}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500" %><br>
          <%= label_tag "release_year_#{year}", year %>
        </div>
      <% end %>
    </div>      
  </div>
  <div class="flex-1 mx-3">
    <div id="genre_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg p-2" onclick="document.getElementById('genres').classList.toggle('hidden');">
      <h5 class="text-white">Genre</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="genres" class="hidden absolute w-60 z-50 text-gray-200 bg-gray-600 border-2 border-black mt-1 p-1 max-h-52 overflow-scroll rounded-sm">
    <% genres = [] %>
      <% Review.pluck(:genre).each do |genre| %>
        <% genre.split(',').map(&:strip).each do |name| %>
          <% if !genres.include?(name) %>
            <% genres << name %>
              <div>
                <%= check_box_tag 'genre[]', name, false, id:"genre_#{name}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500"  %>
                <%= label_tag "genre_#{name}", name %>
              </div>
            <% end %>
          <% end %>
        <% end %>
    </div> 
  </div>
  <div class="flex-1 mx-3">
    <div id="rated_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg p-2" onclick="document.getElementById('ratings').classList.toggle('hidden');">
      <h5 class="text-white">Rated</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="ratings" class="hidden absolute w-60 z-50 text-gray-200 bg-gray-600 border-2 border-black mt-1 p-1 max-h-52 overflow-scroll rounded-sm">
      <% Review.distinct.pluck(:rated).each do |rating| %>
        <div>
          <%= check_box_tag 'rated[]', rating, false, id: "rated_#{rating}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500"  %>
          <%= label_tag "rated_#{rating}", rating %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="flex-1">
    <div id="scores_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg p-2" onclick="document.getElementById('scores').classList.toggle('hidden');">
      <h5 class="text-white">Review Scores</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="scores" class="hidden absolute w-60 z-50 text-gray-200 bg-gray-600 border-2 border-black mt-1 p-1 max-h-52 overflow-scroll rounded-sm">
      <% Review.distinct.order(review_score: :desc).pluck(:review_score).each do |score| %>
        <div>
          <%= check_box_tag 'review_score[]', score, false, id: "rated_#{score}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500" %>
          <%= label_tag "review_score_#{score}", score %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<input type="submit" value="Submit" form="filter-form" class="hidden">

app/views/reviews/_filter_form.html.erb
<%= form_tag filter_reviews_path, id:"filter-form", method: :get, class:"hidden md:w-11/12 max-w-5xl md:flex mt-3 text-base", data: { turbo_action: 'replace', turbo_frame: 'reviews_frame' } do %>
  <div id="years_section" class="flex-1 relative mr-1">
    <div id="release_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center hover:rounded-b-none rounded-t-lg rounded-b-lg items-center p-2" onmouseenter="document.getElementById('release_years').classList.remove('hidden');" 
       onmouseleave="document.getElementById('release_years').classList.add('hidden');"> 
      <h5 class="text-white">Release Year</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="release_years" class="hidden absolute w-full z-50 text-gray-200 bg-gray-600 border-2 border-black p-2 max-h-52 overflow-auto " onmouseenter="document.getElementById('release_years').classList.remove('hidden');" 
       onmouseleave="document.getElementById('release_years').classList.add('hidden');" onmouseenter="document.getElementById('release_modal').classList.add('rounded-b-lg rounded-b-none');" 
       onmouseleave="document.getElementById('release_modal').classList.toggle('rounded-b-lg');">
      <% Review.distinct.order(release_year: :desc).pluck(:release_year).each do |year| %>
        <div class="flex items-center my-1">
          <%= check_box_tag 'release_year[]', year, false, id: "release_year_#{year}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500", form: "filter-form" %><br>
          <%= label_tag "release_year_#{year}", year, class:"w-full" %>
        </div>
      <% end %>
    </div>      
  </div>
  <div id="genre_section" class="flex-1 relative mx-1">
    <div id="genre_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg hover:rounded-b-none p-2" onmouseenter="document.getElementById('genres').classList.remove('hidden');" 
       onmouseleave="document.getElementById('genres').classList.add('hidden');">
      <h5 class="text-white">Genre</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="genres" class="hidden absolute w-full z-50 text-gray-200 bg-gray-600 border-2 border-black p-2 max-h-52 overflow-auto rounded-sm" onmouseenter="document.getElementById('genres').classList.remove('hidden');" 
       onmouseleave="document.getElementById('genres').classList.add('hidden');">
      <% genres = Review.pluck(:genre).flat_map { |genre| genre.split(',').map(&:strip) }.uniq %>
        <% genres.each do |name| %>
          <div class="flex items-center my-1">
            <%= check_box_tag 'genre[]', name, false, id:"genre_#{name}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500", form: "filter-form" %>
            <%= label_tag "genre_#{name}", name, class: "w-full" %>
          </div>
      <% end %>
    </div> 
  </div>
  <div id="rated_section" class="flex-1 relative mx-1">
    <div id="rated_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg hover:rounded-b-none p-2" onmouseenter="document.getElementById('ratings').classList.remove('hidden');" 
       onmouseleave="document.getElementById('ratings').classList.add('hidden');">
      <h5 class="text-white">Rated</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="ratings" class="hidden absolute w-full z-50 text-gray-200 bg-gray-600 border-2 border-black p-2 max-h-52 overflow-auto rounded-sm" onmouseenter="document.getElementById('ratings').classList.remove('hidden');" 
       onmouseleave="document.getElementById('ratings').classList.add('hidden');">
      <% Review.distinct.pluck(:rated).each do |rating| %>
        <div class="flex items-center my-1">
          <%= check_box_tag 'rated[]', rating, false, id: "rated_#{rating}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500", form: "filter-form"%>
          <%= label_tag "rated_#{rating}", rating, class:"w-full" %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="scores_section" class="flex-1 relative ml-1">
    <div id="scores_modal" class="hover:cursor-pointer bg-blue-600 hover:bg-blue-700 flex justify-center items-center rounded-lg hover:rounded-b-none p-2" onmouseenter="document.getElementById('scores').classList.remove('hidden');" 
       onmouseleave="document.getElementById('scores').classList.add('hidden');">
      <h5 class="text-white">Review Scores</h5>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#FFFFFF" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m0 0l6.75-6.75M12 19.5l-6.75-6.75" />
        </svg>
      </span>
    </div>
    <div id="scores" class="hidden absolute w-full z-50 text-gray-200 bg-gray-600 border-2 border-black p-2 max-h-52 overflow-auto rounded-sm" onmouseenter="document.getElementById('scores').classList.remove('hidden');" 
       onmouseleave="document.getElementById('scores').classList.add('hidden');">
      <% Review.distinct.order(review_score: :desc).pluck(:review_score).each do |score| %>
        <div class="flex items-center my-1">
          <%= check_box_tag 'review_score[]', score, false, id: "review_score_#{score}", class:"mr-3 w-4 h-4 border-gray-200 rounded focus:ring-blue-600 ring-offset-gray-700 focus:ring-offset-gray-700 bg-gray-500 border-gray-500", form: "filter-form" %>
          <%= label_tag "review_score_#{score}", score, class:"w-full" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<input type="submit" value="Submit" form="filter-form" class="hidden">

app/views/reviews/_filter_list.html.erb
<div id="filter-conditions">
  <h3>Filter Conditions:</h3>
  <% if filter_conditions.present? %>
    <ul>
      <% filter_conditions.each do |condition| %>
        <li><%= condition %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No filters applied.</p>
  <% end %>
</div>

app/views/reviews/_movie_details.html.erb
<div class="mt-7 flex flex-col w-11/12 justify-center items-center top-14 md:top-20 relative">
  <div class="md:hidden flex justify-between items-center w-full max-w-xl"> 
    <h1 class="font-semibold text-xl self-start max-w-xs"><%= movie_title %></h1>     
  </div> 
  <div class="flex flex-col md:flex-row w-4/5 max-w-4xl">
    <img src="<%= poster %>" class="w-full md:w-auto mt-7 md:mt-0 h-72 md:h-80 object-contain rounded-t-lg">
    <div class="flex w-full md:hidden my-3">
      <span>Movie Details</span>
      <svg id="toggle-btn" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="rotate-180 w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3"/>
      </svg> 
    </div>
    <div id="movie-details" class="text-sm hidden flex justify-between flex-col md:flex md:justify-between md:ml-5">   
      <h1 class="hidden md:inline font-semibold text-xl self-start max-w-xs"><%= movie_title %></h1>     
      <div class="text-gray-500 w-full text-sm flex justify-between md:justify-start">
        <span class="md:mr-3"><%= year %></span>
        <span class="md:mr-3">|</span>
        <span class="md:mr-3"><%= runtime %></span>
        <span class="md:mr-3">|</span>
        <span class="md:mr-3"><%= rated %></span>
        <span class="md:mr-3">|</span>
        <span class="md:mr-3"><%= genre %></span>
      </div>
      <div class="flex flex-col justify-start mt-5 md:mt-0">
        <span class="font-bold text-sm">Director</span>
        <span><%= director %></span>
      </div>
      <div class="flex flex-col justify-start mt-5 md:mt-0">
        <span class="font-bold text-sm">Lead Actors</span>
        <span><%= actors %></span>
      </div>
      <div class="flex flex-col justify-start mt-5 md:mt-0">
        <span class="font-bold text-sm">Awards</span>
        <span><%= awards %></span>
      </div>
      <div class="flex flex-col justify-start mt-5 md:mt-0">
        <span class="font-bold text-sm">Summary</span>
        <span><%= plot_summary %></span>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_search.html.erb
<%= form_with url: search_reviews_path, class:"w-11/12 max-w-5xl flex", method: :get do |form| %>
  <%= form.text_field :query, class: "text-sm max-w-3xl rounded flex-1 ", placeholder: "Search Movie Title, Director, Writer, Actors, Year, Genre", value: params[:query] %>
  <button class="flex-2 hidden md:inline w-32 ml-5 mr-3 text-sm bg-blue-600 border-2 border-blue-600 hover:bg-white text-white hover:text-blue-600 font-normal py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    <%= form.submit 'Search' %>
  </button>
  <button class="flex-2 hidden md:inline w-32 text-sm text-blue-500 border-2 border-blue-500 hover:bg-blue-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    Reset search
  </button>
<% end %> 

app/views/reviews/_search_form.html.erb
<%= form_with url: search_reviews_path, id:"search-input", class:"w-11/12 max-w-5xl flex", method: :get, data: { turbo_action: 'replace', turbo_frame: 'reviews_frame' } do |form| %>
  <%= form.text_field :query, class: "text-sm bg-slate-100 max-w-3xl rounded flex-1 ", placeholder: "Search Movie Title, Director, Writer, Actors, Year, Genre", onkeyup: "submitForm(event)", autocomplete: "off" %>
  <button class="flex-2 hidden md:inline w-32 ml-5 mr-3 text-sm bg-blue-600 border-2 border-blue-600 hover:bg-white text-white hover:text-blue-600 font-normal py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    <%= form.submit 'Search' %>
  </button>
  <button class="flex-2 hidden md:inline w-32 text-sm text-blue-500 border-2 border-blue-500 hover:bg-blue-600 hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline" onclick="resetForms()">
    Reset search
  </button>
<% end %> 

app/views/reviews/show.html.erb
<div id="pageContainer" class="min-h-screen flex flex-col items-center bg-slate-200">
  <%= render partial: 'devise/shared/navbar'%>
  <%= render partial: 'movie_details', locals: { movie_title: @review.movie_title, poster: @review.movie_poster, year: @review.release_year, runtime: @review.runtime, rated: @review.rated, genre: @review.genre, director: @review.director, actors: @review.actors, awards: @review.awards, plot_summary: @review.plot_summary } %>
  <div id="criticDetails" class="w-11/12 max-w-5xl mt-3 top-14 md:top-20 relative">
    <% if user_signed_in? && current_user.role == "admin"%>
      <div class="flex justify-between text-sm bg-gray-300 px-2 py-3">
        <span class="font-bold">Reviewer Options</span>
        <div>
          <%= link_to 'Edit', edit_review_path(@review.id), class:"py-1 px-4 hover:text-white hover:bg-green-500 text-green-500 rounded-md border-2 border-green-500 bg-white"%>
          <span onclick="document.getElementById('modal-<%= @review.id %>').classList.toggle('hidden');" class="cancel-modal review-delete py-1 px-4 hover:text-white hover:cursor-pointer hover:bg-red-500 text-red-500 rounded-md border-2 border-red-500 bg-white">Delete</span>
        </div>
      </div>
    <% end %>
    <div class="mt-5">
      <h3 class="text-base font-bold mb-2">Critic Review</h3>
      <p class="pl-1"><%= @review.review_summary%></p>
    </div>
    <div class="flex justify-between bg-gray-300 mt-5 mb-20 p-3">
      <span>Critic Score</span>
      <span><%= @review.review_score %>/10</span>
    </div>
  </div>
  <%= render partial: 'delete_modal', locals: { id: @review.id, movie_title: @review.movie_title }%>
</div>